---
- name: Setting Up control-plane
  block:
    - name: Initiating Kubernetes cluster
      command: kubeadm init --control-plane-endpoint="{{ ansible_eth1.ipv4.address}}" --apiserver-advertise-address="{{ ansible_eth1.ipv4.address }}" --cri-socket=unix:///var/run/containerd/containerd.sock --pod-network-cidr=10.0.10.0/24

    - name: Setting up kubectl
      command: "{{ item }}"
      loop:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config

    - name: Creating Pod Network
      become: false
      command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
