---
- name: Setting Up workers
  block:
    - name: Generating join token
      command: kubeadm token create --print-join-command
      register: join_cluster_cmd
      delegate_to: "{{ groups['master'][0] }}"

    - name: Setting join variable
      set_fact:
        join_cluster: "{{ join_cluster_cmd.stdout }}"
        cacheable: true

    - name: Joining the cluster
      command: "{{ join_cluster }}"
