---
- name: Provisioning Nodes
  hosts: all
  connection: local
  gather_facts: true

  vars:
    bin_path: '/usr/local/bin'
    ssh_keys_path: '/vagrant/keys'
    ubuntu_pkgs:
      - wget
      - curl
      - htop
      - vim
      - git

    centos_pkgs:
      - epel-release
      - yum-utils
      - wget
      - curl
      - htop
      - vim
      - git

    docker_key:
      'https://download.docker.com/linux/debian/gpg'
    docker_repo:
      'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    docker_compose_src:
      'https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64'

  tasks:
    - name: Provisioning Ubuntu
      become: true
      block:
        - name: Installing Common Pkgs [Ubuntu]
          apt:
            name: '{{ ubuntu_pkgs }}'
            state: latest
            update_cache: yes

        - name: Installing Docker Key [Ubuntu]
          apt_key:
            url: '{{ docker_key }}'
            state: present

        - name: Installing Docker Repo [Ubuntu]
          apt_repository:
            repo: '{{ docker_repo }}'
            state: present
            filename: docker-ce

        - name: Installing Docker Engine Stable [Ubuntu]
          apt:
            name: docker-ce
            state: present
            update_cache: yes
      when: ansible_facts['distribution']=="Ubuntu"

    - name: Provisioning CentOS
      become: true
      block:
        - name: Installing Common Pkgs [CentOS]
          yum:
            name: '{{ centos_pkgs }}'
            state: latest
            update_cache: yes

        - name: Adding Docker repo [CentOS]
          shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

        - name: Installing Docker Engine [CentOS]
          yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-compose-plugin
            state: latest
      when: ansible_facts['distribution']=="CentOS"

    - name: Installing Docker Compose 2.7.0
      become: true
      get_url:
        url: '{{ docker_compose_src }}'
        dest: '/usr/local/bin/docker-compose'
        mode: 755

    - name: Docker Post-install
      become: true
      block:
        - name: Adding existing user to group Docker
          user:
            name: '{{ ansible_user_id }}'
            groups: docker
            append: yes

        - name: Ensuring Docker is started
          service:
            name: docker
            state: started
            enabled: yes

    - name: Setting Connection and Network
      become: true
      block:
        - name: Create SSH directory if it does not exist
          file:
            path: /root/.ssh
            state: directory

        - name: Copying Private Key
          copy:
            src: '{{ ssh_keys_path }}/vagrant-key'
            dest: /root/.ssh/id_rsa
            mode: 400

        - name: Copying Public Key
          copy:
            src: '{{ ssh_keys_path }}/vagrant-key.pub'
            dest: '{{ item.dest }}'
            mode: 400
          loop:
            - { dest: '/root/.ssh/id_rsa.pub' }
            - { dest: '/root/.ssh/authorized_keys' }

        - name: Copying SSH Key to /home dir
          shell: cat /root/.ssh/id_rsa.pub >> /home/{{ ansible_user_id }}/.ssh/authorized_keys

        - name: Setting Hostnames
          shell:
            cmd: 'echo {{ item.host }} >> /etc/hosts'
          loop:
            - { host: "'10.0.10.100 manager.lab'" }
            - { host: "'10.0.10.110 worker01.lab'" }
            - { host: "'10.0.10.120 worker02.lab'" }
            - { host: "'10.0.10.130 registry.lab'" }
